language: julia
os:
- linux
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
julia:
- 1.3
- nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
after_success:
  -julia -c 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
