language: julia
os:
- linux
julia:
- 1.3
- nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
after_success:
  -julia -c 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
