name: Documentation

on:
  push:
    branches:
    - main
    - develop
  pull_request:
    branches:
    - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DISPLAY: ':99.0'
    steps:
    - uses: actions/checkout@v2
    - uses: julia-actions/setup-julia@latest
    - run: sudo apt-get install xvfb -y
      with:
        version: '1.5'
    - run: xvfb-run --auto-servernum julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
    - run: xvfb-run --auto-servernum julia --project=docs/ docs/make.jl
